### ISSUE TITLE
Add opencv

### ISSUE THREAD

**Issue by kokodile** [rationalmatter/Juno-Issue-Tracker#109]
Having an opencv package would be benificial.
https://pypi.org/project/opencv-python/

I believe originally it's based on C++. Not sure anymore.

Please let me know, if it is possible.

**Comment by navoshta** [comment]
Thanks @kokodile, I'll look into it.

**Comment by RavinderSinghPB** [comment]
OpenCv is very important, as it provide image processing, real-time photo capturing and analysis.

**Comment by KaraRyougi** [comment]
It seems opencv-python 3.4.10.37 is on the package manager. However, I failed to install it. It says “Installation from source failed”.

**Comment by navoshta** [comment]
@KaraRyougi Yep, package installer shows all packages that are available on PyPI — although you won't be able to install those with native extensions. Unfortunately, there is no reliable way to tell if a package has native extensions, apart from downloading and attempting to install, this is why Juno can't simply filter out incompatible packages automatically.

**Comment by KudosPower** [comment]
@navoshta Currently, OpenCV is not available in PYPI in Juno anymore. Will it be added after solving? It’s one reason that I decide to buy Juno with more cost instead of other apps. I’m looking forward to getting a solution to this OpenCV installation issue in Juno.

**Comment by navoshta** [comment]
@KudosPower OpenCV is still not available in Juno, although it's certainly on the roadmap (I don't have ETA I'm afraid). I do plan to look into it sooner rather than later though.

**Comment by knagaiwa** [comment]
Please add the OpenCV in Juno. How is the progress?

**Comment by navoshta** [comment]
@knagaiwa I haven't started on it yet I'm afraid, but I will make sure to update this issue when there is some progress, or when it's ready to test in Juno beta.

**Comment by knagaiwa** [comment]
Thank you for teaching me very kindly. I'm hopeful about that.

**Comment by fauzanalif13** [comment]
So is opencv already available yet?

**Comment by alexstaravoitau** [comment]
Sorry @fauzanalif13 not yet — although it's high on the list of packages to add. I'm hoping to wrap up with Juno 2.0 in the next few months, and will be looking into environment upgrade and new packages next.

**Comment by otills** [comment]
Following up on this thread. We have purchased Juno, but require opencv - when is it expected to be supported?

**Comment by alexstaravoitau** [comment]
@otills I don't have an ETA I'm afraid, although it's one of next packages I will be looking into. 

So the timeline is: Juno 2.0 will be released on App Store within a week or so (fingers crossed), and we will begin testing Juno with Python 3.10 on TestFlight pretty much right away after that. We will be upgrading the rest of the environment to latest version next, and then it's adding new packages, of which OpenCV is one of the first we will be looking into. 

Apologies I can't give you more specific ETAs, but releasing 2.0 and upgrading Python to 3.10 turned out to be quite ambitious tasks (which we seem to have finally wrapped up on).

**Comment by otills** [comment]
Thanks for the update, Will this be a free upgrade?

On 18 Nov 2022, at 16:44, Alex Staravoitau ***@***.***> wrote:

﻿

@otills<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fotills&data=05%7C01%7Coliver.tills%40plymouth.ac.uk%7C630468fdc780492e10e208dac9841c44%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638043866488930815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yo5YZC9YjWYC5UrPBICz7PKCn0PRqOgURLXoxQnqd9E%3D&reserved=0> I don't have an ETA I'm afraid, although it's one of next packages I will be looking into.

So the timeline is: Juno 2.0 will be released on App Store within a week or so (fingers crossed), and we will begin testing Juno with Python 3.10 on TestFlight pretty much right away after that. We will be upgrading the rest of the environment to latest version next, and then it's adding new packages, of which OpenCV is one of the first we will be looking into.

Apologies I can't give you more specific ETAs, but releasing 2.0 and upgrading Python to 3.10 turned out to be quite ambitious tasks (which we seem to have finally wrapped up on).

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frationalmatter%2FJuno-Issue-Tracker%2Fissues%2F109%23issuecomment-1320268142&data=05%7C01%7Coliver.tills%40plymouth.ac.uk%7C630468fdc780492e10e208dac9841c44%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638043866488930815%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0X%2FjmU9yI7BoU64rqDDK1RTykEh1Krx%2BFQMtMjVMAk8%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACAB3R4OY5XBZV7PKXRVO53WI6W5NANCNFSM4J4HYN6A&data=05%7C01%7Coliver.tills%40plymouth.ac.uk%7C630468fdc780492e10e208dac9841c44%7C5437e7eb83fb4d1abfd3bb247e061bf1%7C1%7C0%7C638043866489087034%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lNIOrda4E1ZyEqP5Jc%2Flr1UIlAsWWZCPq1eI0viW8v0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________
[http://www.plymouth.ac.uk/images/email_footer.gif]<http://www.plymouth.ac.uk/worldclass>

This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed. If you are not the intended recipient then copying, distribution or other use of the information contained is strictly prohibited and you should not rely on it. If you have received this email in error please let the sender know immediately and delete it from your system(s). Internet emails are not necessarily secure. While we take every care, University of Plymouth accepts no responsibility for viruses and it is your responsibility to scan emails and their attachments. University of Plymouth does not accept responsibility for any changes made after it was sent. Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by alexstaravoitau** [comment]
@otills Yes, Juno 2.0 is a free update

**Comment by 12eggrolls** [comment]
Any updates on adding opencv?

**Comment by alexstaravoitau** [comment]
@12eggrolls Not yet I'm afraid, but it is (still) high on the list of priorities, as it's requested often. We are currently trying to add a few easier/smaller packages first before committing to a bigger job of adding OpenCV.

**Comment by thipokKub** [comment]
What about `opencv-python-headless` version?

**Comment by alexstaravoitau** [comment]
@thipokKub It still comes with binaries that would need to be linked before submitting to App Store (and there are other OS restrictions we need to work around).

Rest assured we've started looking into OpenCV though—still no ETA, but at the very least it should be the next new package released in Juno.

**Comment by alexstaravoitau** [comment]
Juno 3.4.0 comes with OpenCV onboard and is now live on the App Store! 🎉

**Comment by Dsearle2** [comment]
Any chance to support opencv-python-headless?

**Comment by alexstaravoitau** [comment]
@Dsearle2 I assume opencv-python-headless is a subset of opencv-python's APIs, which is already available in Juno—why would you want it over standard opencv-python?
