### ISSUE TITLE
Package install fails

### ISSUE THREAD

**Issue by kingtwirp** [rationalmatter/Juno-Issue-Tracker#127]
**Describe the bug**
Receive error “Failed to install_________ unable to install from source” when trying to install several packages including tables, numexpr.

**To Reproduce**
1. Go to package install icon
2. Tap on package install icon
3. Enter package name (tables and numexpr)
4. Select install package
5. See error

**Expected behavior**
Install appropriate package.

**Screenshots**

**Environment (please complete the following information):**
 - Device: iPad Pro 12.9”
 - iOS version: iOS 13.3
 - App version 1.1.1

**Comment by navoshta** [comment]
@kingtwirp Both tables and numexpr have native extensions: unfortunately, due to platform restrictions only pure Python packages can be installed. Anything that requires compilation for a particular platform needs to be ported and embedded in the app, same as it's done for NumPy, Matplotlib, Pandas, etc. 

You can submit package requests for the packages you want to see in Juno (a separate issue in this tracker for each), and if it gets enough traction I will certainly prioritse it in the list of packages to add. Currently we're primarily working on SciPy: #25.
