### ISSUE TITLE
Can’t input Chinese in Cell

### ISSUE THREAD

**Issue by mieqq** [rationalmatter/Juno-Issue-Tracker#15]
**Describe the bug**
Can only input Chinese by handwriting, not by Pinyin (a method that use English alphabet to enter Chinese characters.）

**Comment by navoshta** [comment]
Unfortunately, there is a known issue with assisted input using latin characters (something similar to IME in Windows, where you use latin characters to input in Japanese, Korean or Chinese). Apparently, this issue is caused by one of the components Jupyter is using, and this issue has been reported, although not resolved yet — see discussion here: https://github.com/codemirror/CodeMirror/issues/3137.

**Comment by mieqq** [comment]
Thanks for your reply, I will go and have a look.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Alex Staravoitau <notifications@github.com>
发送时间: Saturday, June 1, 2019 6:58:00 PM
收件人: rationalmatter/Juno-Issue-Tracker
抄送: mieqq; State change
主题: Re: [rationalmatter/Juno-Issue-Tracker] Can’t input Chinese in Cell (#15)


Unfortunately, there is a known issue with assisted input using latin characters (something similar to IME in Windows, where you use latin characters to input in Japanese, Korean or Chinese). Apparently, this issue is caused by one of the components Jupyter is using, and this issue has been reported, although not resolved yet ― see discussion here: codemirror/CodeMirror#3137<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcodemirror%2FCodeMirror%2Fissues%2F3137&data=02%7C01%7C%7C0dcde0f296024772024808d6e68003c9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636949834829150439&sdata=FyI3wvQ6shNeo5kmin%2BZtvejYtri8PT%2Ffjdqgl5pop4%3D&reserved=0>.

―
