### ISSUE TITLE
uncertainties package fails on import

### ISSUE THREAD

**Issue by ToCkie** [rationalmatter/Juno-Issue-Tracker#166]
**Describe the bug**
```uncertainties``` package fails to load with python 3 kernel.

**To Reproduce**
1. install the ```uncertainties``` package version ```3.1.2``` or ```3.1.1```
2. ```import uncertainties``` will result in the following error message:
```
File "/var/mobile/Containers/Data/Application/XXXXXX/Documents/site-packages/uncertainties/__init__.py", line 224, in <module>
    from .core import *

  File "/var/mobile/Containers/Data/Application/XXXXXX/Documents/site-packages/uncertainties/core.py", line 2921
    POSITIVE_DECIMAL_UNSIGNED_OR_NON_FINITE = ur'((\d*)(\.\d*)?|nan|NAN|inf|INF)'
                                                                                ^
SyntaxError: invalid syntax
```

**Expected behavior**
The package should load and work. (This should be doable since ```uncertainties``` load and work on app Carnets and Pythonista)

**Environment:**
 - Device: iPad Pro 12.9 4th gen
 - iOS version: iOS 13.5
 - App version: 1.2.3

**Comment by navoshta** [comment]
Hi @ToCkie — looks like it's the installation that is the problem here. Uncertainties is a Python 2 package, which relies on starting an external process during installation to convert itself to Python 3. This doesn't sound like an optimal installation approach (and also it isn't possible on iOS due to platform limitations) — luckily, it has been raised in their repo already, and they seem to agree to simply provide wheels for each platform: https://github.com/lebigot/uncertainties/issues/106. As soon as they do that, Juno will be able to use the preferred distribution (Python 3.6 wheel) and install everything correctly.

Meanwhile, you can download the source on desktop, run the conversion manually, and then install resulting Python-3.6-ready package in Juno by putting it into `/site-packages` (or if you use Python 3 on desktop, you can simply copy installed package from your desktop `/site-packages`). Apologies for inconvenience, but there is little we can do on the Juno side of things, and it sounds like package developers are already working on providing a proper Python 3.6 wheel, which will ultimately fix the issue.

**Comment by lebigot** [comment]
Version 3.1.4 has universal wheels. Does this solve issue https://github.com/lebigot/uncertainties/issues/106?

**Comment by lebigot** [comment]
For reference: uncertainties now include universal wheels, which should solve the problem.

**Comment by navoshta** [comment]
Thanks @lebigot — uncertainties seem to install fine now, and the universal wheel is getting correctly picked up as preferred distribution. Looks like their dependency `future` fails to install though, but I will need to look into this (and perhaps simply bundle it in the app).

**Comment by lebigot** [comment]
Thanks for the feedback.

`future` is a new dependency I just added to the code (as there is now a single code base for Python 2 and 3). I am understanding that `future` requires `setuptools`, so that would be another dependency too.

**Comment by navoshta** [comment]
Yep, makes sense @lebigot — I've now also identified an issue that prevented `future` from installing in Juno, which will be fixed in the next app update. When it's released, Juno users will be able to install `uncertainties` and all dependencies in the app. 🎉
