### ISSUE TITLE
package-installation failure

### ISSUE THREAD

**Issue by 7points** [rationalmatter/Juno-Issue-Tracker#171]
**Describe the bug:**
iapws is pure python code.
When trying to install the package, the following message appears:
! Failed to install iapws 1.4.1
Installation from source failed

**Environment (please complete the following information):**
 - Device: Ipad pro version 1
 - iOS version: 13.5.1
 - App version: 1.2.5 (5382)

**Comment by navoshta** [comment]
Hi @7points — apologies for a late reply, I had too look into this a bit further. So, you are right: it should install without issues, but it currently doesn't because of a bug in Juno. ☹️ This applies to _some_ packages that only come as source distributions, and which try to use other packages during installation. A fix will be released in the next Juno update, meanwhile please install manually by placing the package files into _/site-packages_ directory.

**Comment by navoshta** [comment]
@7points this should now be fixed in latest Juno beta (1.2.7) — ping me at beta@juno.sh if you're not on our TestFlight and would like to participate.
