### ISSUE TITLE
Allow installing packages with optional native extensions

### ISSUE THREAD

**Issue by edinghsu31124** [rationalmatter/Juno-Issue-Tracker#176]
**What is the name of the package?**
A name or link to the Python package you think should be pre-installed in Juno. Mind that you can install pure Python packages from PyPI in Juno — those that can be successfully installed won't be embedded in the app.

Hi, I tried to install the “simplejson” package in Juno. It failed to install it. It gives me a feedback of “installation from sources failed. Could you guide me to fix it in Juno? I need this package for yahoo-finance package. Thanks~

**Comment by navoshta** [comment]
Looks like Simplejson is, in fact, a pure Python package, or rather has an option to be installed as a pure Python package. Although this should be possible to do in Juno's package installer, currently it fails due to an unrelated error — I will update the issue title and will look into how this can be enabled.

Meanwhile, you should be able to install Simplejson manually: install on your desktop into a directory, specifying that you don't need native extensions, and then copy resulting pure Python installation into Juno's _/site-packages_ directory.

**Comment by navoshta** [comment]
This should now be fixed in Juno 1.2.8 — you should now be able to install `simplejson` via Juno's package installer, as well as other packages where native extensions are optional.
