### ISSUE TITLE
Google Colab Jupyter Notebook

### ISSUE THREAD

**Issue by verde2006** [rationalmatter/Juno-Issue-Tracker#185]
**Describe the bug**
Unable to aaccess jupyter files as of July 3rd. See screenshot error message %

**To Reproduce**
1. Go to Browse
2. Under Locations, select Google Drive
3. Once inside, click or find Colab folder
4. Select notebook

**Expected behavior**
I expected to at least open the file but cannot open any.
**Screenshots**
Attached

**Environment (please complete the following information):**
 - Device: [iPad 9.7]
 - iOS version: [iOS 13.5.1]
 - App version [1
![4BF2349C-F351-4BDD-8A52-8A45A53AD5B2](https://user-images.githubusercontent.com/12466134/86513464-6ca22880-be02-11ea-9b8b-df2e4efc51ef.png)
![75CA20B5-0519-4DCA-B3B0-93FE3579DEFB](https://user-images.githubusercontent.com/12466134/86513465-70ce4600-be02-11ea-911d-1701712be095.png)

.0.0]

**Comment by navoshta** [comment]
Unfortunately, this is due to Google Drive choosing _not_ to integrate with the iOS Files app in its file provider. Not much Juno can do on its side without them integrating from their end first, I'm afraid — see discussion here: https://github.com/rationalmatter/Juno-Issue-Tracker/issues/96 (I'll close this issue as a duplicate, as both are about Google Drive not letting Juno open .ipynb files).

Also, we are considering to integrate with some cloud providers (say, Google Drive) bypassing Files app — even though it may be a bit tricky, and would certainly add a bit of friction UX wise. Don't have any ETA for this though I'm afraid.
