### ISSUE TITLE
IndentationError

### ISSUE THREAD

**Issue by kadaliao** [rationalmatter/Juno-Issue-Tracker#194]
Always get `IndentationError: unindent dose not match any outer indentation level`, and then I have to reinput those lines one by one, very frustrating.

I'm using iPad Pro with Magic Keyboard. 

![image](https://user-images.githubusercontent.com/7401626/88778132-b2ac9b00-d1ba-11ea-8844-801407173904.png)

**Comment by zekekoch** [comment]
I had the same problem on two lines.

**Comment by navoshta** [comment]
Interesting — thanks for reporting @zekekoch and @kadaliao! From the screenshot it looks like the code is correctly indented. Do you see this with every notebook, or only with specific ones? Could you send me a notebook that shows this error by any chance? Perhaps there are some odd Unicode whitespace characters in it, or something like this.

**Comment by kadaliao** [comment]
@navoshta I see it in every notebook, matter what its content is. Just like @zekekoch gets this problem with two lines code.

Seems like there is something is wrong with `<tab>` key and the auto indent stuff. 

When I copy the content of the cell to other editors like 'Vim', it actually shows odd whitespaces.

By the way, my device and os:

- iPad Pro 2020, 12.9 ich
- iPadOS 13.6

I haven't used Juno on other device and system before. 

#### sample notebook
[notebook.zip](https://github.com/rationalmatter/Juno-Issue-Tracker/files/5011740/notebook.zip)

**Comment by navoshta** [comment]
Thanks @kadaliao — yep, the problem is that the notebook has non-whitespace characters, which look like ordinary whitespace. More specifically, correct lines all consist of U+0020 (SPACE) characters, whereas the lines that Python is complaining about are, in fact, a combination of U+0020 (SPACE) and U+00A0 (NO-BREAK SPACE) characters.

Now we simply need to figure out how those non-breaking space characters end up in the notebook. For example, this is what the notebook you have attached looks like in text editor: 

<img width="241" alt="Screenshot 2020-08-05 at 15 44 41" src="https://user-images.githubusercontent.com/1111935/89426985-a2ed0380-d732-11ea-9374-cc39b593f702.png">

...The line that starts with `def __init__...` looks OK — it uses correct Unicode characters. Whereas the next line, the ones that starts with `super().__init__...` has erroneous non-breaking spaces. Any chance you could experiment and check _when_ those non-break spaces are inserted? Does it happen when you tap the Tab key on the keyboard extension, on top of the on-screen keyboard? Or when you simply hit Tab key on the hardware keyboard, or maybe when you hit space key?

**Comment by kadaliao** [comment]
@navoshta 

It happens when I try to unindent by deleting spaces with `<Ctrl-h>` key combo.

[video screen capture](http://st.kada.ink/juno_unindent_demo.mp4)

I use Ctrl key almost everywhere..., please fix it :) 😂

**Comment by kadaliao** [comment]
And also with the iPhone version Juno, you will get the Indent problem even if you are using `<delete>` key.

**Comment by navoshta** [comment]
Thanks for looking into this further @kadaliao — I managed to reproduce it, looks like a WebKit and/or CodeMirror issue. I will see how I can workaround this!

**Comment by alexstaravoitau** [comment]
Juno 2.1 with updated Jupyter and CodeMirror is now live on App Store — hopefully fixing the issue.
