### ISSUE TITLE
When I switch from another app to Juno always get to see the „Juno-hourglass“.

### ISSUE THREAD

**Issue by jplasser** [rationalmatter/Juno-Issue-Tracker#207]
**Describe the bug**
Switching from another app to Juno one has to wait before Juno gets productive. It displays the Juno hourglass (whatever this is called).

**To Reproduce**
1. Open Juno and a Notebook, run some cells
2. Switch to another app(s), do something
3. Switch back to Juno after some time
4. See the "hourglass" and wait before Juno opens the Notebook

**Expected behavior**
I want to have immediate access to the Notebook.

**Environment (please complete the following information):**
 - Device: iPad Pro 11", 2018
 - iOS version: iOS 14.0.1
 - App version 1.2.8

**Comment by navoshta** [comment]
Hi @jplasser — I'm afraid this is due to how iOS treats 3rd party apps in general (see #48 and #83, for example). In short, OS only lets 3rd party apps like Juno remain in background for a little bit, suspending them after some (brief) period. When Juno is back on screen, it will try to do its best to restore your context back to where it was. I understand it's not ideal, and we're hoping to improve this behaviour in future, ideally letting Juno remain in background longer, or improving restart times.

**Comment by jplasser** [comment]
Thanks for your answer! Let's hope iOS/Apple change this in future.
Juno is one of my favorite apps!

**Comment by navoshta** [comment]
Thanks @jplasser 😇 — I'll close this issue for now, but feel free to reopen or create a new one if you realise Juno doesn't restore its context when it should, for example.
