### ISSUE TITLE
Unable to connect to remote Jupyter Lab server

### ISSUE THREAD

**Issue by Hans0124SG** [rationalmatter/Juno-Issue-Tracker#220]
I just purchased Juno Connect and trying to connect to the remote server in my university. I am connecting to my school’s VPN and am able to ssh into the server via Terminus. However, when I try to connect to the Jupyter Lab server, I get the below message:
<img width="678" alt="PNG image" src="https://user-images.githubusercontent.com/18539093/100443754-3f258680-30e5-11eb-92ba-c6492b769129.png">
This is my setting:
<img width="667" alt="PNG image 2" src="https://user-images.githubusercontent.com/18539093/100443847-69774400-30e5-11eb-977c-48443a536907.png">

Could you help take a look and see why? Thanks a lot!

**Comment by navoshta** [comment]
Hi @Hans0124SG — can you check if there are any messages in Jupyter console, if you have access to it? 

It looks like Juno Connect is trying to load an HTTPS address rather than HTTP, which is the default for port forwarding connections. When you typically connect to this server on desktop, which address do you use in your browser after SSH tunnel is established? Is it `http://localhost:8000`, or `https://localhost:8000`, or something else?

**Comment by Hans0124SG** [comment]
I use http://localhost:8000. Sorry I don't have the access to the Jupyter console.

**Comment by navoshta** [comment]
Hope you got it resolved @Hans0124SG — alternatively, feel free to reach out to help@juno.sh, and I'll try to assist further.

**Comment by Hans0124SG** [comment]
Dear Alex,

Yeah I have got it solved, it was to due the server issue. Thanks a lot!

Best Regards,
Wang Han
