### ISSUE TITLE
App keeps loading forever

### ISSUE THREAD

**Issue by kar-man** [rationalmatter/Juno-Issue-Tracker#231]
App keep refreshing after minimizing

**To Reproduce**
1. Minimize Juno app
2. Wait for few seconds
3. Open Juno app
4. App takes significant amount of time in refreshing

**Comment by navoshta** [comment]
Hi @kar-man — I'm afraid this is due to how iOS treats 3rd party apps in general (see #48 and #83, for example). In short, OS only lets 3rd party apps like Juno remain in background for a little bit, suspending them after some (brief) period. When Juno is back on screen, it will try to do its best to restore your context back to where it was. I understand it's not ideal, and we're hoping to improve this behaviour in future, ideally letting Juno remain in background longer, or improving restart times.

Does it finish loading eventually? If the app gets stuck while trying to load, then this is a bug of course, and I will need to look into it (there were similar reports about this).

**Comment by kar-man** [comment]
Yes, most of the times it restores to the last session. But sometimes it keeps loading forever. Need to quit and reopen. I didn't see such issues with apps like Carnet or Pythonista 3 etc. Anyway if possible please fix these issue. Thanks

**Comment by navoshta** [comment]
Thanks for reporting @kar-man — yep I've received a couple of similar reports regarding Juno getting stuck on loading, and will look into this. I can't find a relevant open GitHub issue, so will leave this one open and will edit the title.

**Comment by alexstaravoitau** [comment]
Juno 2.1 significantly improves background persistence (2.1 is now live on App Store), and app loading should have been addressed in earlier releases, too.
