### ISSUE TITLE
Add requests

### ISSUE THREAD

**Issue by sprague252** [rationalmatter/Juno-Issue-Tracker#237]
The `requests` package is an HTTP library with much of the functionality of curl. According to the documentation, it was once included in a python runtime app for iOS. Right now, it is not possible to install requests on Juno because it requires the `cryptography` package, which is not supported on Juno.

https://requests.readthedocs.io/en/master/

**Comment by navoshta** [comment]
@sprague252 We are planning to add `cryptography` soon regardless, but it seems to be optional when installing `requests`. Did you try installing it in Juno, and it gave you an error? Or did you get an error when you tried to import the installed module, or something like that?

<img width="565" alt="Screenshot 2021-02-05 at 17 21 16" src="https://user-images.githubusercontent.com/1111935/107067027-9ecf9a80-67d6-11eb-8cb2-769b1f93f677.png">

**Comment by sprague252** [comment]
I was not aware that cryptography was optional. Sorry. I was installing the requests dependencies and stopped when cryptography was not available. Regardless, you should consider making requests one of the built-in packages.

I will try installing requests without cryptography and let you know.

**Comment by sprague252** [comment]
I was able to install requests without the cryptography module, and it works fine for my purposes. Thanks for your help.

**Comment by navoshta** [comment]
Glad you managed to install it @sprague252 — the idea is to ship Juno with as few pre-installed packages as possible, because pre-installed packages can not be upgraded/downgraded currently. So if a package can be installed without issues via package installer, I'd rather let the user install it and choose whichever version they want. But I do have plans to improve this by suggesting to install commonly used packages automatically, or something like that.

**Comment by sprague252** [comment]
Thanks again! It is working without any issues for my purposes.
