### ISSUE TITLE
Add scipy 

### ISSUE THREAD

**Issue by smkirby** [rationalmatter/Juno-Issue-Tracker#25]
https://www.scipy.org/scipylib/index.html

**Comment by SuperTachyon** [comment]
Scipy is the most important missing package for me. It’s probably not easy to port but others have done it (Pyto).

**Comment by reichardtj** [comment]
Same here, scipy is one of the very important packages missing and a lot of others depend on it, eg seaborn. Happy to contribute if possible.

**Comment by rayandaod** [comment]
Just wanted to thank you for your work, Juno is really a great app on Ipad Pro. Scipy is also a very important package for me and some packages I would like to use also depend on it (e.g librosa). Let me know if I can be of any help with this!

**Comment by navoshta** [comment]
Thanks @rayandaod!

**Comment by CZspf** [comment]
Is there a timeline when it will be ready?  I really need scipy on remote devices.

**Comment by navoshta** [comment]
Unfortunately there is no ETA at the moment, but judging by how it's progressing I'd say it should be available early next year. I'm trying to avoid any remotely precise estimates: for example, when I was porting NumPy, I was fairly confident it was ready to ship at some point, but then it took me another month or two to make it _actually_ ready to ship. 😀 

By the way, I know there are existing iOS ports of NumPy available on GitHub (as well as Matplotlib, Pandas and even SciPy), and we did look into those — unfortunately, they wouldn't work in Juno for a number of reasons, primarily because how Juno operates under the hood. In order to minimise memory and overal performance footprint, Juno utilises several non-conventional optimisation approaches for running Python interpreter and Jupyter server all at once. They need to be taken into account when building native extensions for non pure Python packages (e.g. NumPy, Matplotlib, Pandas, and now SciPy too), so typically we have to port and build those libraries from scratch for Juno. Furthermore, ARM versions of Pandas and SciPy that are currently available all seem to be using questionable workarounds in order to get them to work on iOS; instead, we are trying to avoid those in order to make our process more sustainable — so that we could update Juno's native extensions with relative ease when new libraries are released, and make sure they provide as much functionality as possible for the platform. I hope this provides some reasoning of why we have to port all those embedded libraries ourselves, and why it takes a while! 🙂

As per progress on SciPy: it's now built successfully, and we are currently at the stage of ironing out a (pretty large) number of failing tests. It's really hard to tell when it will be good enough to integrate in Juno, hence no ETA — but it's certainly getting there. 🙃 And of course once SciPy is fully embedded, this will pave the way for a whole lot of other packages that depend on it, scikit-learn and scikit-image to name a few!

**Comment by CZspf** [comment]
Looking foward to it. For me pandas, matplotlib, and scipy really tell ios devices from laptops. Good to know it is almost done.

**Comment by PyMarc2** [comment]
Hello! Just for a monthly update, how is it looking? :) Looking forward to it!!

**Comment by wudaudau** [comment]
Looking forward for it!!

**Comment by navoshta** [comment]
@PyMarc2 Apologies for a late reply — we're still working on it, and we're on the same stage or ironing out various issues across SciPy modules (it has many!). 

I'm hoping to start beta-testing in coming weeks (depending on how bug fixing progresses), with a build that will likely be not production ready, but will help us collect more bug reports. SciPy has a lot of bits and pieces, and we may not be able to test all of them on our own. Whenever this happens, I will certainly post here, inviting more people to test!

**Comment by PyMarc2** [comment]
Great!! Keep up the good work!! 😀

**Comment by PyMarc2** [comment]
I’m ready to test in pre pre alpha production launch ahaha

**Comment by navoshta** [comment]
Good news, everyone! SciPy is looking good in general, and while there are still a few random crashes, it should be ready for beta while we fix those. 

Juno 1.2 is now waiting for TestFlight review, and should be available in the next few days — please send an e-mail to beta@juno.sh if you would like to help test it!

**Comment by navoshta** [comment]
SciPy 1.4.0 is now available to everyone as Juno 1.2 is now live on App Store. Thank you for your patience! 🎉
