### ISSUE TITLE
Is Tensorflow available on Juno?

### ISSUE THREAD

**Issue by SakamotoYuki** [rationalmatter/Juno-Issue-Tracker#254]
I am on the verge of purchasing the app, I am wondering if tensorflow is available on Juno, the last issue was created in 2019, and there hasn’t been an update.
I am also wondering if there is a list of supported packages. on the juno doc it says “only pure Python packages are supported” 
So I’m not sure which ones are already ported/being ported

thanks

**Comment by navoshta** [comment]
Hi @SakamotoYuki! TensorFlow is still not supported I'm afraid — adding TF is an ambitious project, and I haven't got to it yet I'm afraid. When there are some developments in that area I'll make sure to update the original GitHub issue, so you can just subscribe to that. 

As per packages currently available, there is a list of the most popular packages that have been 'ported' here: https://juno.sh/troubleshooting-juno#what-packages-does-juno-have. There are a few others that are included with Juno, but these here are the ones that have their native extensions specifically built for iOS, which means you wouldn't be able to install them otherwise.
