### ISSUE TITLE
Add-Question (python-control)

### ISSUE THREAD

**Issue by 4DimK** [rationalmatter/Juno-Issue-Tracker#292]
Hello, before purchasing the app, I am trying to figure out whether the Python Control Systems Toolbox (python-control) package is/can be installed. From https://python-control.readthedocs.io/en/0.9.0/intro.html#installation the dependencies are numpy, scipy and matplotlib which seem to be embedded into the app. Would that work?

**Comment by alexstaravoitau** [comment]
Hi @mksk4 — judging by the package description it looks like a pure Python package, so *should* work. Package installer shows an error when trying to install it, but that's because it was packaged in an outdated format (hopefully package authors will update it eventually). 

It seems to work if you just download and unzip sources manually into *site-packages*. If you can add a code example I can give it a go and tell you if it works or not. 🙃

**Comment by 4DimK** [comment]
Hi @navoshta - Thank you for your reply! So, I purchased the app and installed the control package. Indeed automatic installation failed, but manually placing the source files under site-packages/ seems to have done the trick. Therefore, indeed it work as you said!

I believe this add request can be considered successfully closed, thank you!
