### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by dhruvahuja17** [rationalmatter/Juno-Issue-Tracker#300]
We have got a feature within the app to edit our keyboard commands and shortcuts. It is mentioned that all our changes will be saved for our further sessions.

But that doesn’t seem to hold true. We have to edit those shortcuts every time we open a new project or continue with the same project.

**Comment by alexstaravoitau** [comment]
Hi — unfortunately, Juno doesn't allow editing keyboard shortcuts at the moment, neither should it mention anywhere that they are configurable (because they are not). Could you please send me a screenshot of which settings you mean exactly? Perhaps I'm missing something, and the issue is not keyboard shortcuts, but something else?

**Comment by dhruvahuja17** [comment]
> We have got a feature within the app to edit our keyboard commands and shortcuts. It is mentioned that all our changes will be saved for our further sessions.
> 
> 
> 
> But that doesn’t seem to hold true. We have to edit those shortcuts every time we open a new project or continue with the same project.
> 
> 
>

**Comment by dhruvahuja17** [comment]
![image](https://user-images.githubusercontent.com/99337834/154219134-3bc326da-552d-42fe-99a2-fc7065e82e7b.png)
Steps to **Edit Command Mode Shortcuts**
1) Open a new notebook
2) Click on the Notebook name (for new notebook it will be named as untitled)
>Click on Jupyter Commands
Or 
Go to Command mode and push 'P'
3) Click on search bar, and search 'edit command board keyboard shortcuts'
4) Click on 'edit command board keyboard shortcuts'
5) Edit the Command that you wish

**Comment by alexstaravoitau** [comment]
Thanks for reporting @dhruvahuja17 — this is an accidentally exposed piece of internal Jupyter functionality which Juno does not support at the moment. Sadly, for the time being the fix would be to remove this menu so that it's not shown at all, but I do hope to introduce configurable shortcuts in future in some other form.
