### ISSUE TITLE
please support python module dataprep

### ISSUE THREAD

**Issue by eddo888** [rationalmatter/Juno-Issue-Tracker#312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by alexstaravoitau** [comment]
Hi @eddo888 — looks like `dataprep` is a pure Python package, so you should be able to install it using Juno's package installer. Or does it not work as expected?

**Comment by eddo888** [comment]
ininstall dataprep then dask andbi get this

  File "/var/mobile/Containers/Data/Application/1C900F10-D4FF-4A63-A101-D7781C44191E/Documents/site-packages/dask/config.py", line 1
    from __future__ import annotations
                                      ^
SyntaxError: future feature annotations is not defined

thanks for your help

![image](https://user-images.githubusercontent.com/2610223/161892171-85aa0863-19a0-4d63-90d2-5930ec0cab60.png)

![image](https://user-images.githubusercontent.com/2610223/161892184-0521c2c7-e922-4ddc-a32e-335177281766.png)

**Comment by alexstaravoitau** [comment]
@eddo888 `annotations` is only available in Python 3.7 and later, whereas Juno comes with Python 3.6. We are currently working on upgrading our Python environment, so it will become available in one of future updates. 

Since this is not a `dataprep` issue, I'll be closing this ticket — but feel free to reopen if some part of `dataprep` package specifically doesn't work.
