### ISSUE TITLE
Juno is always loading 

### ISSUE THREAD

**Issue by gaoyuanhezhihao** [rationalmatter/Juno-Issue-Tracker#346]
<img width="1366" alt="截屏 2023-03-03 21 09 56 png 2" src="https://user-images.githubusercontent.com/11392359/222728665-c4565142-b9d6-4837-bb2d-629c1969a1a5.png">
When I open any ipnb file, it will loading forever. Thank you in advance.

**Comment by gaoyuanhezhihao** [comment]
I am sure it is caused by some addresses are blocked by my network whitelist. But I have put juno.sh into the whitelist. So are there any other addresses used by Juno app?

**Comment by alexstaravoitau** [comment]
Hi @gaoyuanhezhihao — this looks like it could indeed be because of a blocked address (or because of parental/other content restrictions enabled on device). You'd need to whitelist **localhost** in order for Juno to work — and I'll make sure to improve the error handling in the notebook editor for this case, too.

**Comment by gaoyuanhezhihao** [comment]
Yes, it works after I add 'localhost' to my whitelist. Thank u very much.
