### ISSUE TITLE
Add requests, datetime,json

### ISSUE THREAD

**Issue by ParzivalWins** [rationalmatter/Juno-Issue-Tracker#37]
**What is the name of the package?**
Here's a list of requested packages:
requests
datetime
json

Thank you in advance.

**Comment by navoshta** [comment]
As of Juno 1.0.4, you can install pure Python packages using Juno's package installer — which seems more reasonable rather than trying to include everything in the bundle. 

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-09-07 at 12 01 25](https://user-images.githubusercontent.com/1111935/64474090-46bae180-d167-11e9-99ee-3c3466b99dfb.png)

Simply provide package name (the one you would use with `pip` command), and it will let you select package version and install into your `/site-packages` directory. Mind that dependencies are **NOT** installed automatically, you need to install each manually. Also, installer is "stateless", which means it doesn't keep track of what has been installed previously, and simply overwrites whatever is currently installed. If you would like to remove a package, simply delete its folder in `/site-packages` directory.

Please, reopen or create a new issue if you spot a pure Python package that won't install, or if you need a package with native extensions.
