### ISSUE TITLE
Missing ML Frameworks

### ISSUE THREAD

**Issue by fraxx001** [rationalmatter/Juno-Issue-Tracker#374]
**Is your feature request related to a problem? Please describe.**
Currently no ML Frameworks like onnx, onnxruntime, tensorflow 2.x and PyTorch are supported.

**Describe the solution you'd like**
Making Hose packages available for Juno.

**Comment by alexstaravoitau** [comment]
Thanks for reporting @fraxx001 — I assume this is about Juno, not Juno Connect? Juno Connect should let you use any packages that are installed on the Jupyter server you are connecting to.

I'll close this issue, because there are already package requests for TensorFlow (#39) and PyTorch (#35), and feel free to submit a separate issue for onnx. I'm certainly planning to look into adding one of those, but this is likely a huge job which will take a lot of effort and time. We are currently focusing on resolving more of the "low hanging fruit" package requests, but I do plan to look into bringing PyTorch or TensorFlow at some point.
