### ISSUE TITLE
[Question] Notebook Extensions in Juno

### ISSUE THREAD

**Issue by iamrecursion** [rationalmatter/Juno-Issue-Tracker#395]
I can't find any documentation on this, but I've been wondering if it is possible to load notebook extensions such as [myst](https://mystmd.org/guide/quickstart-jupyter-lab-myst) in Juno. They fundamentally affect both the server and renderer, so I can understand why it wouldn't be supported.

I've given that one in particular a go, and not had any luck, but without any documentation saying it is possible I have no idea if I have just done something wrong or whether it fundamentally does not work!

Any info would be most appreciated!

**Comment by alexstaravoitau** [comment]
I'm afraid this isn't possible right now. Juno doesn't support installing notebook extensions, and the notebook editor in Juno is based on a substantially modified version of Jupyter Notebook rather than JupyterLab. However, I do plan to switch to a version of JupyterLab in the future and may revisit supporting extensions in some form.

**Comment by iamrecursion** [comment]
Okay, that makes sense! I figured that would be the case! Thanks for letting me know!
