### ISSUE TITLE
Add **torch** and ** torchvision** (again)

### ISSUE THREAD

**Issue by plucaci** [rationalmatter/Juno-Issue-Tracker#434]
**What is the name of the package?**
The PyTorch and torchvision libraries, it appears they say "Not compatible" despite this feature having been requested 5 years ago...

**Comment by alexstaravoitau** [comment]
Hey @plucaci—yep PyTorch is a popular request, but is a huge task, and I'm not even 100% sure it would work in Juno due to iOS platform restrictions. You could try my other app Juno Connect, which lets you connect to a Jupyter server remotely and work on your notebooks from iPad or iPhone. With that kind of setup you can use whichever packages are installed on the Jupyter server you are connecting to.
