### ISSUE TITLE
Add sympy

### ISSUE THREAD

**Issue by slabko** [rationalmatter/Juno-Issue-Tracker#5]
**What is the name of the package?**
https://www.sympy.org/en/index.html

**Comment by hydroclaus** [comment]
When I do `from sympy.stats import Binomial`, I get the following error. 

> ModuleNotFoundError: No module named 'sympy'

Does this mean, I have to install it myself ([into the site-packages folder](https://github.com/rationalmatter/Juno-Issue-Tracker), but what exactly should I put there), or should it be there, because it was added on May 7th?

**Comment by navoshta** [comment]
@hydroclaus `sympy` hasn't been added to Juno yet, although looks like it's a pure-Python module, so you should be able to install it by simply putting it into the `site-packages` folder — that is, the unarchived `sympy-1.4` folder you can download from [sympy.org](https://www.sympy.org).

**Comment by dar10p** [comment]
Tried to do this: download and put it into <site-packages> but didn't work.

**Comment by navoshta** [comment]
Hi @dar10p — sorry for a late reply, I've tried putting sympy and its dependency mpmath into site-packages and managed to import them fine. Make sure to only put the _sympy_ and _mpmath_ folders though, not the .tar.gz downloads:

![IMG_4581](https://user-images.githubusercontent.com/1111935/62555523-02d47400-b86b-11e9-9853-3908580a1da4.PNG) ![IMG_4582](https://user-images.githubusercontent.com/1111935/62555529-0536ce00-b86b-11e9-81db-71a4afd050f8.PNG)

**Comment by dar10p** [comment]
Thx! That was the issue. I'd just put the full tar... Now it works!

**Comment by hydroclaus** [comment]
@dar10p  @navoshta  Thanks for pointing this out and uploading the screenshots. My site-packages folder looks now exactly like yours.
I still get the error `no module named 'sympy'`.
Is there a way to force/ensure iOS to download an entire folder (i.e. all files in the `site-packages` folder including subfolders)?

**Comment by navoshta** [comment]
@hydroclaus This folder should be in your on-device storage, so nothing should be offloaded I assume?

Also, next Juno release will have a (hopefully) easier way to install packages.

**Comment by navoshta** [comment]
As of Juno 1.0.4, you can install pure Python packages (such as SymPy) using Juno's package installer — which seems more reasonable rather than trying to include everything in the bundle. 

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-09-07 at 12 01 25](https://user-images.githubusercontent.com/1111935/64474090-46bae180-d167-11e9-99ee-3c3466b99dfb.png)

Simply provide package name (the one you would use with `pip` command, e.g. "sympy"), and it will let you select the version and install it. Mind that dependencies are NOT installed automatically, you need to install each manually — mpmath in case of SymPy.
