### ISSUE TITLE
Please add request package

### ISSUE THREAD

**Issue by eoss-tw** [rationalmatter/Juno-Issue-Tracker#52]
Request lib provides nifty http api to python. To support easier access to web apis would be very cool for a tablet python environment.

**Comment by navoshta** [comment]
Hi @eoss-tw, if you mean [Requests](https://pypi.org/project/requests/#description), it should be available via package installer. 

I agree that it would be convenient to include some commonly used packages by embedding them in Juno. On the other hand, I want to embed as few things as possible, because I don't allow upgrading packages that are pre-installed (yet). This is to make sure users don't accidentally override a module which is necessary for the app itself to function. So, by embedding a package I essentially "lock" its version, which some users would not like either, if a new package version is released, or if they require some particular (older) version.

Please, feel free to reopen if I misunderstood.
