### ISSUE TITLE
[Developer] Building non-pure Python packages for Juno

### ISSUE THREAD

**Issue by banesullivan** [rationalmatter/Juno-Issue-Tracker#62]
I develop Python packages that I’d love to explore leveraging on iOS/iPadOS.  If a package is not pure Python, what might the developer of a package need to provide in order to install that package on Juno?

**Comment by navoshta** [comment]
Good question! Due to platform restrictions, all packages using native extensions need to embed their compiled binaries in the app (i.e. you can't install them externally, as there's no way to link afterwards). 

So, perhaps the best way would be to add a package request ticket here, and make sure native extensions in your package are implemented in as platform agnostic manner as possible, i.e. can be easily cross-compiled for iOS.

**Comment by DRTorresRuiz** [comment]
Hello, I am trying to install **rpy2 3.2.0 package** on *Juno for Jupiter Notebook* , but once I click on the install button I receive this error:

    “⚠️Failed to install rpy2 3.2.0. Installation from source failed” 

Could this also be related to this topic?

**Comment by banesullivan** [comment]
> perhaps the best way would be to add a package request ticket here, and make sure native extensions in your package are implemented in as platform agnostic manner as possible, i.e. can be easily cross-compiled for iOS.

Thanks for the tip! For the package that I am most interested in adding [the visualization toolkit](https://vtk.org)'s Python bindings, this is a lot easier said than done and it will likely be a while before a stable iOS version is released.

So I suppose this answers my question!
