### ISSUE TITLE
Unable to enter Chinese

### ISSUE THREAD

**Issue by Bollie15** [rationalmatter/Juno-Issue-Tracker#68]
I can't type in Chinese, it doesn't work. I don't want to update to IOS13, because after I upgraded my ipad mini5 to the ipad OS, I regretted that many of the apps were not compatible. I don't want to upgrade the system.

 - Device: [iPhone XR]
 - iOS version: [iOS 12.1]
 - App version [Juno 1.0.0(4127)]
The following link video is the problem. There is no problem with the software itself. However, I need to input Chinese to make some notes. After all, my English is not very good.I hope you can settle it as soon as possible.

[bug_video.zip](https://github.com/rationalmatter/Juno-Issue-Tracker/files/3749101/bug_video.zip)

**Comment by navoshta** [comment]
Thanks @Bollie15 — since it's related to iOS 12, looks like this issue duplicates #27 (I'll close this one and leave the older one open). 

As mentioned in the comments there, I'll see if I can apply a workaround specifically for iOS 12. Alternatively, I highly recommend updating to iOS 13 — hopefully, other apps received updates and fully support it by now.

**Comment by Bollie15** [comment]
@navoshta Thanks
