### ISSUE TITLE
Image display

### ISSUE THREAD

**Issue by kilichenko** [rationalmatter/Juno-Issue-Tracker#71]
Does not display images inserted as html tag

Steps to reproduce the behaviour:
Insert in a markdown cell a tag like `<img src="test.png">`
Run the cell and contemplate a perfectly empty square. The same notebook displays the image correctly when opened on the desktop. 

I used iPad mini 5 on iOS 13. Notebook and image are in the same dropbox folder. App is updated.

![photo_2019-10-29_20-27-19](https://user-images.githubusercontent.com/26851756/67802277-1a4a8400-fa8b-11e9-8ec8-964562fdb103.jpg)

**Comment by navoshta** [comment]
@kilichenko This is expected behaviour I'm afraid: in order to display the image, Juno need to have access to the image file. Judging by the icon in the header, Juno doesn't have access to notebook directory, so it can't read the image. You can verify this by moving said notebook and image to another location, e.g. Juno's on-device storage. 

You will get similar behaviour if notebook and image are in the Juno's iCloud folder, but the image is _not downloaded to the device_, by the way.

**Comment by kilichenko** [comment]
Thank you, actually bought iPad recently specifically to use Juno, so I'm new to the platform. I guess there is no way here to grant the necessary privileges to the app? What is then the recommended way of syncing notebooks if storing them locally?

**Comment by navoshta** [comment]
@kilichenko For most cloud providers you should be able to grant access with that folder-with-a-lock button in the notebook editor top bar. Dropbox app, however, doesn't seem to fully conform to iOS file provider integration requirements, so unfortunately it doesn't work with it (yet). It should work with iCloud though, or with Working Copy repos, and with other apps that fully integrate against iOS's file system APIs. But then again, the image file in your example above should be downloaded to device for it to become available to Juno.
