### ISSUE TITLE
Dash Module incomplete 

### ISSUE THREAD

**Issue by paulllemke** [rationalmatter/Juno-Issue-Tracker#77]
On PiPy, there is a Module called CoolProp, which i imported succesfully. But since it is not a pure Python Package, i was not able to use it. Also, there is a Module for Dash in PiPy, but ist seems like ist is not complete. When i tryed to run my code, ist told me that multiple sub-modules could not be found. With some of them, i was able to install them, but with some others ( e.g. dash_renderer
 ), it was not possible, even if i found them on pypi. 

First of all, i would love to see coolprop being available on Juno. Second of all, i would like you to solve or tell me how Top solve the problem with dash.

Mit freundlichen Grüßen
Paul Lemke

**Comment by navoshta** [comment]
@paulllemke, there seems to be a bug in Juno's package installer, which won't display package info for `dash-renderer` as some of the package info is missing. This will be fixed in the next release — thanks for reporting!

As per CoolProp, please create a separate ticket using "package request" template.

**Comment by navoshta** [comment]
Package installer should now display info for `dash-renderer` correctly.
